[package]
name = "openmesh"
version = "0.1.0"
authors = ["Ashish Myles <marcianx@gmail.com>"]

[dependencies.nalgebra]
[dependencies.bitflags]
[dependencies.byteorder]
[dependencies.num]
[dependencies.downcast-rs]

