[package]
name = "openmesh"
version = "0.1.0"
authors = ["Ashish Myles <marcianx@gmail.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.6"
bitflags = "1.3.2"
bitvec-rs = "0.2"
byteorder = "1.4.3"
downcast-rs = "^1"
num = "0.1"

