[package]
name = "openmesh"
version = "0.1.0"
authors = ["Ashish Myles <marcianx@gmail.com>"]

[dependencies]
nalgebra = "0.6"
bitflags = "0.4"
bitvec-rs = "0.1"
byteorder = "0.4"
downcast-rs = "^1"
num = "0.1"

